version: "3.1"
networks:
  greetings-service-network:
services:
  greetings-service-api:
    build: .
    ports:
      - "3333:3456"
    environment:
      PORT: 3456
      DATABASE_URI: "postgres://postgres:password@greetings-service-database:5444/postgres"
      JWT_SECRET: "some-secret-for-jwt"
    depends_on:
      - postgres
    networks:
      - greetings-service-network
    command:
      ["./wait_for_it.sh", "greetings-service-database:5444", "--", "node", "index.js"]

  postgres:
    image: postgres
    container_name: greetings-service-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql
    ports:
      - 5444:5432
    networks:
      - greetings-service-network
